version: '3.4'

services:
  backoffice.webapi:
    image: ${DOCKER_REGISTRY-}backofficewebapi
    build:
      context: .
      dockerfile: Backoffice.WebApi/Dockerfile    
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1q2w3e4r
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/dev_cert.pfx
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - db
    volumes:
      - ./conf.d/https/:/https/

  db:
    image: "mcr.microsoft.com/mssql/server:2017-CU11-ubuntu"
    environment:
      SA_PASSWORD: "@A1q2w3e4r"
      ACCEPT_EULA: "Y"
    ports:
     - "1401:1433"
    volumes: 
     - D:/mssql:/var/opt/mssql/data

  backoffice.frontend:
    image: ${DOCKER_REGISTRY-}backofficefrontend
    build:
      context: ./backoffice.frontend
      dockerfile: Dockerfile
    volumes:
      - "./backoffice.frontend:/app"
      - "./app/node_modules"
    ports:
      - "8080:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true